### ISSUE TITLE
Problem with 'PluginName vVERSION'

### ISSUE THREAD

**Issue by NuppDEV** [strumswell/ServerlistMOTD-X#1]
Hey. I get this error when i start my server:
[18:08:18 WARN]: [ServerlistMOTD] The author of this plugin (Strumswell) has misconfigured their Auto Update system
[18:08:18 WARN]: [ServerlistMOTD] File versions should follow the format 'PluginName vVERSION'
[18:08:18 WARN]: [ServerlistMOTD] Please notify the author of this error.
Can you help me?
I have latest version of protocollib, and I tried with 6 versions of serverlistmotd.

**Comment by strumswell** [comment]
I was able to recreate your observations and decided to not change the format. This means:
1. The auto updater will **NOT** find any new updates on servers using ServerlistMOTD below X.
2. You will keep getting a warning which will **NOT** affect the functionality of this plugin.

Why I decided to brick the auto updater:
1. The automatic download of ServerlistMOTD X on BungeeCord servers is going to cause some trouble due to dropped support.
2. You should update if you are running a Spigot server.

**Comment by NuppDEV** [comment]
[19:34:19 ERROR]: Parameters: 
 net.minecraft.server.v1_8_R3.PacketStatusOutServerInfo@6556a48c[
 b=net.minecraft.server.v1_8_R3.ServerPing@1c97e998
 ]
Some more errors:
https://pastebin.com/mCGX6KrZ

**Comment by strumswell** [comment]
Thanks, are you using the %randomplayer% variable? I'm start recreating this problem now and will keep you updated.

**Comment by strumswell** [comment]
Which version of Smotd and ProtocolLib are you using? Can you also include your config.yml?

**Comment by strumswell** [comment]
Thank you so much for reporting this. It's really hard to find those edge cases!

The problem: You have some very old UUIDs in the IP_UUID.dat that are no longer recorded in the usercache.json (from Spigot) or in the playerdata folder inside your world folder. 

Please test this fix and tell me if it helped: [ServerlistMOTD.jar.zip](https://github.com/strumswell/ServerlistMOTD-X/files/2498450/ServerlistMOTD.jar.zip)

Thanks a lot!

**Comment by strumswell** [comment]
I'm going to close this now. The newest release fixed the bug. If you still have problems, please open up a new ticket.

**Comment by strumswell** [comment]
Bug got fixed in the last release. I'm going to close this now. If you still have problems, please open up a new ticket.
