### ISSUE TITLE
Spigot 1.16.1 support

### ISSUE THREAD

**Issue by Srborjaa** [strumswell/ServerlistMOTD-X#10]
Hi, that's not an issue, but could you upgrade the plugin to 1.16.1? 

Thanks

**Comment by strumswell** [comment]
Not in my hands due to ProtocolLib dependency. Check https://github.com/dmulloy2/ProtocolLib/issues/880 for updates on a ProtocolLib version for 1.16

**Comment by strumswell** [comment]
I reopened the issue to support Spigot 1.16.1 by disabling the ProtocolLib dependency. I attached a patched version in this comment but please proceed with caution:
- See this as a beta
- By removing ProtocolLib many things won't work. Basically every feature manipulation the slots and restricted mode)

But everything else should work normally. You can switch to the latest official release [here](https://github.com/strumswell/ServerlistMOTD-X/releases) when there is a working ProtocolLib version for 1.16.1.

[ServerlistMOTD_2020-06-18-HF.jar.zip](https://github.com/strumswell/ServerlistMOTD-X/files/4842072/ServerlistMOTD_2020-06-18-HF.jar.zip)

**Comment by ClientKitty** [comment]
Wait... So will I still be able to have custom motds?

**Comment by strumswell** [comment]
Sure. ClassicMotd, RandomMotd, BanMotd and WhitelistMotd should all be working. But the [Slots](https://github.com/strumswell/ServerlistMOTD-X/blob/d9021f3e1b3f315a74e53f31900c6f84bc7f4535/config.yml#L49) section in the config will be broken until there is a new ProtocolLib version. Otherwise, everything should be working. Customise your motd, use some variables, whatever. I guess it's a tolerable workaround. :)

**Comment by ClientKitty** [comment]
Ok, thanks
