### ISSUE TITLE
Remove "Add bullet points to add more Motds!"

### ISSUE THREAD

**Issue by borjxrroyo** [strumswell/ServerlistMOTD-X#20]
Hi there,
When I run Minecraft on my computer the motd is shown correctly, but when I use mobile apps as MineChat sometimes the following motd is shown: "Add bullet points to add more Motds!"

My config: https://pastebin.com/0Je5VbW4

**Comment by strumswell** [comment]
Not sure what's going on on your side, but I can't and won't give support for a 3rd party mobile app. Your config looks fine, did you reload your config with /sl reload? Maybe your app serves a cache, I don't know.

**Comment by borjxrroyo** [comment]
The config is saved since days ago, and I think you could help me since this problem is present in some servers (not only with PickaxeChat) https://i.gyazo.com/b77da5ee1dbdff7c9b7087b7aa42b72f.png

Please get informed before rejecting a report.

Thanks in advance.

**Comment by strumswell** [comment]
That's absolute madness. Let me tell you four things:
1. I provide this plugin absolutely for free and still maintain it after 6 years. Nobody pays me for this work. How dare you come here and insist on support and say things that are not true.
2. What kind of report is this please? How could I find out anything with this little amount of information? You don't provide a version of Spigot (is it even Vanilla Spigot?!), ServerlistMOTD or ProtocolLib. Were there any errors?
If you look into the source code, you will notice that the motds come directly from the config and are taken over after the server has been started or the config has been reloaded by /sl reload. They are also directly transferred to the Minecraft client via standard apis. I'm not doing any magic here that could confuse third party developers.
4. I have no influence on how and when third party services/ apps read the MOTD. When it's displayed correctly in Minecraft, the problem lies with the third party service providers. Easy as that. Possible problems could certainly be things like caching of old entries on their side. If you change the motd and reload the config, you can be 100% certain those new entries are getting served to MC clients.

Telling me to get informed is the most impudent thing I've ever heard. Before you tell the developer of his own project to inform himself, you should inform yourself. Look into the code and understand how it works. If you then find a bug, I will gladly apologize and follow up. But if you can't do that, you shouldn't come here with such a big mouth and demand someone to do things you have no idea of.

Now get off my lawn!

**Comment by borjxrroyo** [comment]
Not all the Minecraft server admins have a big knowledge at coding and investigating in Java code, that's because the plugins' developers (normally) have a section to solve doubts for those users. A section that is not present in your plugin (you don't have Discord iirc).

Many authors solved me a lot of doubts with patience, a thing you don't seem to have.

A normal developer when gets doubts worries about the problems of their users, even if the plugin is free.

So I recommend you to have a little bit of patience and not kick out in a bad way those users, or else your plugin popularity will be disastrous.

I also recommend you not to close the reports, the users have also their opinions. Yours is not the only one that exists.

Changing plugin, thanks for nothing.

**Comment by strumswell** [comment]
Let me tell you something: I don't care about popularity and how many people are using this plugin. I don't give a shit. I told you very friendly that this is not a problem related to this plugin, whereupon you hit the completely wrong tone. Of course I am no longer friendly and patient after something like that. If you look into many of those closed issues, I am always friendly and trying to help if the people come in with respect and kindness as well. 

> I also recommend you not to close the reports, the users have also their opinions. Yours is not the only one that exists.

This has nothing to do with opinions. It's about facts. 

If you find actual mistakes, you are welcome to open an issue again. I am the last one who doesn't admit mistakes, they are human. But pay attention to your tone and the things you think you can demand.

**Comment by borjxrroyo** [comment]
I'll tell you a last thing. Then think what you want.

If my review was deleted, it will be for something, right? If I hadn't my reasons you would have left the comment where it was.

Greetings.

**Comment by strumswell** [comment]
I deleted it because this whole conversation is bullshit and you know it. You gave the first negative comment I ever got. Just because you don't like me telling you the truth doesn't mean you are entitled to write bs on my plugin page.
