### ISSUE TITLE
BanMOTD not working with WhitelistMOTD

### ISSUE THREAD

**Issue by Lukas2021** [strumswell/ServerlistMOTD-X#26]
When I have both banmotd and whitelistmotd enabled only the whitelistmotd messages ever show for all combinations of ban/unban/whitelist/not whitelisted. I'm on Paper 1.16.5 with the latest version of the plugin and ProtocolLib.

**Comment by strumswell** [comment]
Hey, this is expected behavior. All motd extensions (whitelist, ban, restricted mode) have a priority resulting in one motd being able to overwrite another one. The priorities are the following, from lowest to highest: Spigot Banmotd, MaxBans Banmotd, BanManager Banmotd, WhitelistMotd, RestrictedMode motd [(source)](https://github.com/strumswell/ServerlistMOTD-X/blob/b8c9951d693330fd78619c70240405d9ec90cfff/src/cloud/bolte/serverlistmotd/motd/MotdState.java#L67). So WhitelistMotd always overwrites a BanMotd.

If it's not that urgent, give me some time and you will get a modified version of ServerlistMOTD with your expected behavior.
