### ISSUE TITLE
VersionText: Version incompatible!

### ISSUE THREAD

**Issue by LcyDev** [strumswell/ServerlistMOTD-X#38]
**Describe the bug**
![image](https://user-images.githubusercontent.com/72966048/144728283-f881a2e1-39f8-4784-982f-ef8471b4f60d.png)

**To Reproduce**
  VersionText:
    Enable: true

**Expected behavior**
![image](https://user-images.githubusercontent.com/72966048/144728296-7364f029-8753-4d4d-8d05-68c95221982d.png)
(Edited with photoshop)

**Config**
https://pastebin.com/EYRar75D

**Versions (please complete the following information):**
 - git-Purpur-1171 (MC: 1.16.5)
 - ServerlistMOTD vX-2021-11-23
 - ProtocolLib 4.7.0 && 4.8.0-SNAPSHOT-b538 (happens in both)

**Comment by strumswell** [comment]
Hey,

this is not a bug but expected behavior due to technical limitations. You can find explanations for that in your config.yml or the [FAQ in my wiki](https://github.com/strumswell/ServerlistMOTD-X/wiki/1.-FAQ#in-the-serverlist). Copy of wiki explanation:

`"The connection bars turn red in the serverlist with VersionText on.": Have you ever seen when your server is outdated in the serverlist and displays some text near the signal bars? SMOTD simulates this and changes the text. This is just a cosmetical change and doesn't influence the functionality of your server.`

There is also a very similar issue created last year you can read up on: https://github.com/strumswell/ServerlistMOTD-X/issues/5
