### ISSUE TITLE
Plugin completely failing

### ISSUE THREAD

**Issue by Gamersxp6248** [strumswell/ServerlistMOTD-X#39]
**Describe the bug**
It appears that the plugin does not function at all, changing the config.yml yields 0 change to the MOTD.

**To Reproduce**
1.18 server
Installed plugin
Changed randommotd to some funny quotes
did /serverlist randommotd
the motd lines are still default even after restart
after restart the config.yml is reset to be completely default

**Expected behavior**
The plugin to actually work and use the random motds put in the config.yml? also to not rewrite the config.yml every single restart

**Config**
It's literally resetting to the default config.yml

**Versions (please complete the following information):**
 - Spigot 1.18.1
 - ServerlistMOTD I assume latest
 - ProtocolLib Also latest
 
 I just installed all of this stuff, and never usually have this problem

**Additional context**

**Comment by strumswell** [comment]
Hey, thanks for reporting. I know of multiple instances where the current version is working as expected. Can you please attach your *changed* config.yml (which resets) here, as instructed during creation of this report? (maybe via pastebin) YAML files can be very tricky sometimes. :) Otherwise, I have no way to reproduce your problem.

**Comment by strumswell** [comment]
Ticket was open for 2 weeks. OP never responded, no one else with the same problem responded and the issue was not reproduce-able.

Please re-open the ticket with more info, if you still have this problem.
