### ISSUE TITLE
[Feature Request] Do not discontinue

### ISSUE THREAD

**Issue by triesharder** [strumswell/ServerlistMOTD-X#55]
Your plugin has some fancy features that the others do not offer. BY FAR

I know there's no rest for the wicked but i came here to ask you to keep up with the good work. 

Set up a license checker in the code, sell the continued version of the plugin on mcmarket(builtbybit), spigot, your own site, dunno.

Having a revenue from the plugin would make it worth of some of your time?

**Comment by strumswell** [comment]
Heyo, thanks for your kind words and you seemingly liking the plugin. That's why I was/ am doing this. :) 

This plugin is officially discontinued since April 2018 as my life and my priorities have changed dramatically. I started working on this when I was 15 and completely rewrote, extended, and open-sourced the project in 2018 while being at university. My idea was to create a future-proof base that server owners can use for the coming years and even extend if they want to. 

Back then I also thought about uploading the plugin to Spigot or even make a paid version out of it. I decided against uploading it on Spigot because of a few trends I noticed back then:
- A lot of cool plugins were (are still?) behind a paywall which is is totally against my personal beliefs. Such software should be free, usable, and extendable by everyone. Especially in a space where a lot of kids are creating servers for them and their friends. I've been there and enjoyed trying out every possible plugin without paying a dime and build something cool. For me, this ecosystem was my entry point to development by the way.
- I despise the entitlement of some plugin users on the Spigot site. People get the ability to (sometimes falsely) judge on plugins that are mostly provided to them for free. If you don't like something, bring it up the discussions part of Spigot nicely. But don't expect that people do the shit you want to. After all, this is a hobby for many plugin developers and I've seen many people burn out over this behavior. Even though I exclusively distribute via dev.bukkit and GitHub, I've also encountered some people being entitled. But at least I have the power to kill their bs comments/ threads.

Coming back to ServerlistMOTD being discontinued since 2018: You might have noticed that there were 9 releases with bug fixes and even feature additions since then. I am not promising anything at all anymore but sometimes I take time and fix bugs or add features if I have the time and feel the itch besides my full time development job. 

That being said, I won't create a paid version of ServerlistMOTD where I commit and fully maintaining this project. But I welcome anyone writing PRs adding new features or fix bugs. This thing will be kept freely usable and extendable by everyone which is also ensured by the license I chose back then (CC BY-NC-SA 3.0).

(PS: You should be able to use this plugin as longs as ProtocolLib gets updates. If they die, you will still be able to use the plugin with a limited feature set. The APIs I am using should be very stable.)
