### ISSUE TITLE
Bugged and missing characters in the MOTD

### ISSUE THREAD

**Issue by Tousend1000** [strumswell/ServerlistMOTD-X#56]
So, I have a bug, I have a Minecraft Server on *Paper 1.19.2* with the *latest version* of ServerlistMOTD *and* ProtocolLib.
I've set my *MOTD* to
```
- '&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&f&l MilkSMP &f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&r'
- '   &7/discord    &f&l|   &f&lVanilla SMP   &f&l|    &7/milkmenu'
```
and the result is ok, so the [MOTD](https://i.imgur.com/sHJwHJ0.png) is how it is supposed to be, but with some bugs:
- There are Braces at the First Position and the Last Position
- The Version is outdated? (Without ServerlistMOTD the version was fine)
- There is a comma at the end of the first line
- There are missing Spaces at the beginning of every line

My whole *config.yml* file is [here](https://pastebin.com/bpG5QEXK)

I am waiting for answers, thanks!

**Comment by strumswell** [comment]
This is not a bug, you're making a mistake in the config. You can not create a new line in the ClassicMotd section by using new bullet points. You have to use the '%line%' variable. Your config section should look like this:
```
ClassicMotd:
  Regulars: '&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&f&l MilkSMP &f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&r%line%   &7/discord    &f&l|   &f&lVanilla SMP   &f&l|    &7/milkmenu'
  Newbies: '&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&f&l MilkSMP &f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&7*&f-&r%line%   &7/discord    &f&l|   &f&lVanilla SMP   &f&l|    &7/milkmenu'
```
This behavior is also outlined in the wiki: https://github.com/strumswell/ServerlistMOTD-X/wiki/2.-ClassicMOTD

About the version outdated: This is known and expected behavior. Please read the wiki, the FAQ in the config.yml, or one of the many issues that have raised the same point:
- https://github.com/strumswell/ServerlistMOTD-X/wiki/1.-FAQ#in-the-serverlist
- https://github.com/strumswell/ServerlistMOTD-X/issues/5

In the future, please read the wiki and FAQ to reduce unnecessary issues. :)
